// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSyx8m9vZdQLeIFvl8ucDwaoT0CZvnyRM',
    appId: '1:237412137186:web:199d850bf301b5685946bb',
    messagingSenderId: '237412137186',
    projectId: 'mobileprac',
    authDomain: 'mobileprac.firebaseapp.com',
    storageBucket: 'mobileprac.appspot.com',
    measurementId: 'G-G2TJQ892DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSgL1tEN1qxXH_IYrV3XbBOJoTTXqjChI',
    appId: '1:237412137186:android:e2b81d77a4c205735946bb',
    messagingSenderId: '237412137186',
    projectId: 'mobileprac',
    storageBucket: 'mobileprac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwIOXWIPTLG9u2k_VToCB-_3mvHSs-3Zc',
    appId: '1:237412137186:ios:7fb553d2251141605946bb',
    messagingSenderId: '237412137186',
    projectId: 'mobileprac',
    storageBucket: 'mobileprac.appspot.com',
    iosBundleId: 'com.example.newprac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwIOXWIPTLG9u2k_VToCB-_3mvHSs-3Zc',
    appId: '1:237412137186:ios:7fb553d2251141605946bb',
    messagingSenderId: '237412137186',
    projectId: 'mobileprac',
    storageBucket: 'mobileprac.appspot.com',
    iosBundleId: 'com.example.newprac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSyx8m9vZdQLeIFvl8ucDwaoT0CZvnyRM',
    appId: '1:237412137186:web:2ebd17c5f6531a5d5946bb',
    messagingSenderId: '237412137186',
    projectId: 'mobileprac',
    authDomain: 'mobileprac.firebaseapp.com',
    storageBucket: 'mobileprac.appspot.com',
    measurementId: 'G-JEZQQ0L05W',
  );

}